# Generated by Django 2.0.3 on 2018-04-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='subreddits.Subreddit'),
        ),
    ]
