# Generated by Django 2.0.3 on 2018-04-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
