# Generated by Django 2.0.3 on 2018-04-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('date', 'topic', 'id'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
