# Generated by Django 2.0.3 on 2018-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180403_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('subreddit', 'created', 'id'), 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topic',
            new_name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
